project_id = "lqlxxoiecjqzvhzcueda"

[functions.manage-cluster]
verify_jwt = false

[functions.k8s-chat]
verify_jwt = false

[functions.ado-proxy]
verify_jwt = false

[functions.ado-scan]
verify_jwt = false

[functions.uptime-check]
verify_jwt = false

[functions.vm-agent]
verify_jwt = false